spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/visualization?serverTimezone=GMT&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: zkc2002318
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: Echarts-provider
mybatis:
  type-aliases-package: com.zhang.pojo
  mapper-locations: classpath:dao/*.xml
server:
  port: 8081